#!/bin/sh
# build-data.sh — Generates data-bundle.js from JSON data files.
# Run this after editing any JSON file in data/.
# Usage: ./build-data.sh   (or: sh build-data.sh)

set -e
DIR="$(cd "$(dirname "$0")" && pwd)"
DATA_DIR="$DIR/data"
OUT="$DIR/data-bundle.js"

cat > "$OUT" <<'HEADER'
/* Auto-generated by build-data.sh — do not edit manually.
   Edit the JSON files in data/ and re-run: sh build-data.sh */
window.STREAMGRID_DATA = {};
HEADER

for key in meta components features milestones pricing competitive; do
  case "$key" in
    meta)         file="plugin-meta.json" ;;
    components)   file="components.json" ;;
    features)     file="features.json" ;;
    milestones)   file="milestones.json" ;;
    pricing)      file="pricing-tiers.json" ;;
    competitive)  file="competitive-analysis.json" ;;
  esac

  if [ ! -f "$DATA_DIR/$file" ]; then
    echo "WARN: $DATA_DIR/$file not found, skipping." >&2
    continue
  fi

  printf 'window.STREAMGRID_DATA.%s = ' "$key" >> "$OUT"
  cat "$DATA_DIR/$file" >> "$OUT"
  printf ';\n' >> "$OUT"
done

echo "Built $OUT ($(wc -c < "$OUT") bytes)"
